{{- if .Values.frontend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "graph-app.fullname" . }}-frontend
  labels:
    {{- include "graph-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}
{{- if .Values.backend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "graph-app.fullname" . }}-backend
  labels:
    {{- include "graph-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
